# Generated by Django 5.2.8 on 2025-11-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_userprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
    ]
