# Generated by Django 5.2.8 on 2025-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_chessgame_player_black_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='board_fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100),
        ),
    ]
