"""
Django settings for chess_core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from corsheaders.defaults import default_headers
from environ import Env
env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Env.read_env()
env.read_env(os.path.join(BASE_DIR, '.env'))
ENVIRONMENT = env('ENVIRONMENT', default="production")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development': 
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = ['pr-reviewer.servehttp.com', 'localhost', '127.0.0.1', "chess-django-backend-production.up.railway.app", "chess-next-frontend-production.up.railway.app"]
CORS_ALLOWED_ORIGINS = [
    "https://chess-next-frontend-production.up.railway.app",
    "http://pr-reviewer.servehttp.com:3000"
]
CSRF_TRUSTED_ORIGINS = ["http://pr-reviewer.servehttp.com:3000", "https://chess-django-backend-production.up.railway.app", "https://chess-next-frontend-production.up.railway.app"]

CHANNELS_WS_ALLOWED_ORIGINS = [
    "https://chess-next-frontend-production.up.railway.app",
    "http://pr-reviewer.servehttp.com:3000"
]

# Channels-specific

CORS_ALLOW_HEADERS = list(default_headers) + [
    "sec-websocket-protocol",
    "sec-websocket-extensions",
]

CHANNELS_ALLOWED_ORIGINS = [
    "https://chess-next-frontend-production.up.railway.app"
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third party
    "corsheaders",
    'ninja_extra',
    'ninja_jwt',
    'rest_framework',
    'rest_framework_simplejwt',
    # internal
    'useraccount',
    'game',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'chess_core.urls'

AUTH_USER_MODEL = 'useraccount.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'chess_core.wsgi.application'
ASGI_APPLICATION = 'chess_core.asgi.application'


# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     }
# }

# railway's redis for channel
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [env('REDIS_URL')],
        },
    },
}

CELERY_BROKER_URL = env('REDIS_URL')

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# postgress from docker container
if ENVIRONMENT == 'development':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres',              # The default DB name
            'USER': 'postgres',              # The default superuser name
            'PASSWORD': 'postgres',          # Your specified password
            'HOST': 'localhost',             # Connects to the host port
            'PORT': '5432',
        }
    }
else:
    # railway's postgress db
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(env('DATABASE_URL'))
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


MEDIA_ROOT = BASE_DIR/'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

CORS_ALLOW_ALL_ORIGINS=True

# this runs the matchmaking task every 300ms
CELERY_BEAT_SCHEDULE = {
    "matchmaking-every-300ms": {
        "task": "game.task.matchmaking_task",
        "schedule": 0.6,  # Run every 600 milliseconds
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}